export {
  Modal,
  ModalBody,
  ModalClose,
  ModalContent,
  ModalDescription,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  ModalPortal,
  ModalTitle,
  ModalTrigger,
} from "./Modal";
export type {
  ModalBodyClassNames,
  ModalBodyProps,
  ModalContentClassNames,
  ModalContentProps,
  ModalDescriptionClassNames,
  ModalDescriptionProps,
  ModalFooterClassNames,
  ModalFooterProps,
  ModalHeaderClassNames,
  ModalHeaderProps,
  ModalOverlayClassNames,
  ModalOverlayProps,
  ModalTitleClassNames,
  ModalTitleProps,
} from "../../types/modal";
