export {
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
} from "./Dialog";
export type {
  DialogBodyClassNames,
  DialogBodyProps,
  DialogContentClassNames,
  DialogContentProps,
  DialogDescriptionClassNames,
  DialogDescriptionProps,
  DialogFooterClassNames,
  DialogFooterProps,
  DialogHeaderClassNames,
  DialogHeaderProps,
  DialogOverlayClassNames,
  DialogOverlayProps,
  DialogTitleClassNames,
  DialogTitleProps,
} from "../../types/dialog";
